name: taxi_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  pin_code_fields: ^8.0.0
  lucide_icons: ^0.257.0
  # camera: ^0.11.1
  permission_handler: ^11.4.0
  share_plus: ^10.1.4
  flutter_facebook_auth: ^6.0.2
  mongo_dart: ^0.10.3
  
  country_picker: ^2.0.0
  provider: ^6.1.2
  google_maps_flutter: ^2.10.1
  intl: ^0.20.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  flutter_localizations:
     sdk: flutter
  flutter_secure_storage: ^9.2.4
  # google_mlkit_face_detection: ^0.12.0
  flutter_polyline_points: ^2.1.0
  url_launcher: ^6.3.1
  mailer: ^6.4.1
  fl_chart: ^0.70.2
  flutter_map:
  latlong2: 
  location: 
  http:
  geocoding:
  webview_flutter: ^4.10.0
  webview_flutter_web: ^0.2.3+4
  webview_flutter_wkwebview: ^3.18.4
  flutter_compass: ^0.8.1
  record: ^5.2.1
  audioplayers: ^6.4.0
  flutter_sound: ^9.27.0
  file_picker: ^9.2.1
  excel: ^4.0.6
  flutter_map_tile_caching: 10.1.1  
  agora_rtc_engine: ^6.5.1
  # google_ml_kit: ^0.19.0
  flutter_dotenv: ^5.2.1
  socket_io_client: ^2.0.3+1
  shared_preferences: ^2.5.3
  cloud_firestore: ^5.6.8
  universal_html: ^2.2.4
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1
  shimmer: ^3.0.0
  js: ^0.6.7


  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 
flutter:
  uses-material-design: true
  assets:
    - assets/image-removebg-preview.png
    - assets/image-removebg-preview1.png
    - assets/image-removebg-preview2.png
    - assets/image-removebg-preview3.png
    - assets/image-removebg-preview4.png
    - assets/image-removebg-preview5.png
    - assets/telegram_icon.png

    - assets/map.png
    - assets/osm_map.html
    - assets/taxi_drivers.xlsx
    - .env
    - assets/adham.png
    - assets/logo.png
    - assets/light_background.png
    - assets/dark_background.png